### ISSUE TITLE
add restful interface

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qiita#1251]
Even so that having one have been the idea since the beginning, I couldn't find an issue to keep track of progress.

**Comment by colinbrislawn** [comment]
Would this sort of interface allow for uploading as well as downloading? I'm working with a medium sized data set, and downloading data to a local machine just upload to qiita is painful. Methods to upload to qiita directly from a linux server using only a CLI, or through a globus endpoint say, would be awesome!

Thanks Antonio!
Colin

**Comment by antgonza** [comment]
This is a good idea, we should figure out a way to do this.

**Comment by antgonza** [comment]
@colinbrislawn, note that we just added a scp/sftp mechanism for quick upload to qiita, original PR: https://github.com/biocore/qiita/pull/2662 and this should be available after Monday's update.

**Comment by colinbrislawn** [comment]
Thanks Antonio. Can't wait to try it! If it's as easy as @osfclient, then I'll start using Qiita much more!

**Comment by antgonza** [comment]
IMOO much easier ... but of course, I'm bias ... 😉

**Comment by antgonza** [comment]
Closing as we have an [internal REST-API](https://qiita.ucsd.edu/static/doc/html/dev/rest.html) and based on the latest plugins and connections to other packages it seems to be working just fine - however, to access it, developers need to request and justify an admin level access (which the rest-provides). For general public access we have this open issue: https://github.com/qiita-spots/qiita/issues/1480.
