### ISSUE TITLE
Add a layer of interoperability between visual displays

### ISSUE THREAD

**Issue by ElDeveloper** [qiita-spots/qiita#1388]
The results page in QIITA, should be able to work as a cohesive unit. Currently each display of information is entirely independent even though they are all representing the same samples. A pressing use-case would be to be able to click on a sample in emperor and then show the taxonomic profile of that sample.

**Comment by antgonza** [comment]
this will be cool as discussed before but not sure this is a feature request in qiita or in emperor or qiime2, @ElDeveloper, what do you think?

**Comment by ElDeveloper** [comment]
I think this is an issue for all the visualization packages that consume
data, and for Qiita, which ultimately would have to handle the relaying
of the messages. Though this is dependant on how we wanted to
architecture this in the end.

**Comment by antgonza** [comment]
I believe this can be closed as this should be provided by QIIME2 or a new JS library, as discussed during today's KL meeting. 

cc-ing @kwcantrell, so he's aware of this conversation.
