### ISSUE TITLE
sample template downloads with the study id prepended

### ISSUE THREAD

**Issue by jwdebelius** [qiita-spots/qiita#1396]
Adding the study id to the sample id (as noted above). <br> Which may or may not be challenging for users, collaborators, and people who don't use pandas to update/build their metadata. ...Excel users can get around it, but they probably won't like it. If I were primarily using Excel, I would not like it. (I find it challenging, but can work around it).

**Comment by josenavas** [comment]
What is the main issue that you're finding with having the study id prepended? There has been long discussions about this and is not trivial, so more background on the issues that you are facing will be more useful.

**Comment by JWDebelius** [comment]
Sorry, just noticed the response.

It is *common* in the studies that I do that a collaborator will sometimes be able to find more data. Maybe they weren't initially motivated, but they found it later. Maybe they were running other tests, and wanted to see what came out of the microbiome before they got that data. Maybe something got delayed, it doesn't really matter. Someone - the collaborator or I - is in a position where additional columns need to be correctly added to the sample template.

Updating the sample template therefore means going into some program - Excel, pandas, etc - and matching the ID to the new data. This, in and of its self, can be a time consuming process, especially if you work primarily in Excel. Having the study id attached to the sample name adds the additional, and possibly error-prone step of having to remove this, so you can check that the sample IDs are the same, and then merge the results. It seems like something the system should do automatically to facilitate handling the data more easily.

**Comment by josenavas** [comment]
I would like to have the input from the other devs here, but my suggestion will be to have a checkbox that allows you to download the data w/o the study id, and de-activated by default.

Note, if you have a new mapping file, you can directly "update" the one in Qiita w/o needing to match the names, it will prepend the study_id automatically. You can then upload the new mapping file, so you don't have to actually merge that. You should be able to upload a sample template with only the new columns, and the system will do the sample name matching for you. I think this is easier than you downloading the template and doing the merge by yourself, right?

**Comment by JWDebelius** [comment]
That still puts the work on the user to round trip, twice.

I'd argue that by default, data should be downloaded without the study id.
You've made what feels like a major change to the column, and this alters
the feel of the data in a way that's very different than standardizing
missing fields or boolean values.

It seems like it should be trivial on your end to just do regex before
download and have the template come down basically the same way it went up.

**Comment by rob-knight** [comment]
Yes, this is a very reasonable request (essentially: add metadata by
matching the ids without the study name, report failures to match).

On Aug 26, 2015, at 3:40 PM, J W Debelius <notifications@github.com> wrote:

Sorry, just noticed the response.

It is *common* in the studies that I do that a collaborator will sometimes
be able to find more data. Maybe they weren't initially motivated, but they
found it later. Maybe they were running other tests, and wanted to see what
came out of the microbiome before they got that data. Maybe something got
delayed, it doesn't really matter. Someone - the collaborator or I - is in
a position where additional columns need to be correctly added to the
sample template.

Updating the sample template therefore means going into some program -
Excel, pandas, etc - and matching the ID to the new data. This, in and of
its self, can be a time consuming process, especially if you work primarily
in Excel. Having the study id attached to the sample name adds the
additional, and possibly error-prone step of having to remove this, so you
can check that the sample IDs are the same, and then merge the results. It
seems like something the system should do automatically to facilitate
handling the data more easily.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1396#issuecomment-135197669>.

**Comment by rob-knight** [comment]
I think for meta-analysis the study id should be included; for samples all
from one study, the user should have option to suppress the study id for
download. Altering metadata should presumably be handled on a per-study
basis and therefore being able to do it with new data that has the original
ids associated (not necessarily the full spreadsheet, maybe just a new
column or two) would be extremely helpful.

On Aug 26, 2015, at 3:53 PM, J W Debelius <notifications@github.com> wrote:

That still puts the work on the user to round trip, twice.

I'd argue that by default, data should be downloaded without the study id.
You've made what feels like a major change to the column, and this alters
the feel of the data in a way that's very different than standardizing
missing fields or boolean values.

It seems like it should be trivial on your end to just do regex before
download and have the template come down basically the same way it went up.

On Wed, Aug 26, 2015 at 3:44 PM Jose Navas <notifications@github.com> wrote:

> I would like to have the input from the other devs here, but my suggestion
> will be to have a checkbox that allows you to download the data w/o the
> study id, and de-activated by default.
>
> Note, if you have a new mapping file, you can directly "update" the one in
> Qiita w/o needing to match the names, it will prepend the study_id
> automatically. You can then upload the new mapping file, so you don't have
> to actually merge that. You should be able to upload a sample template
with
> only the new columns, and the system will do the sample name matching for
> you. I think this is easier than you downloading the template and doing
the
> merge by yourself, right?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/biocore/qiita/issues/1396#issuecomment-135198256>.
>

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1396#issuecomment-135199566>.

**Comment by antgonza** [comment]
If we all agree, I think the option to download any of the templates (sample, prep, qiime) without study_ids is doable.

**Comment by josenavas** [comment]
I agree that is doable, however, I still think the default should be with the study_id. The reason behind this is that all the demultiplexed files and the OTU table have the study_id prefixed so any user that wants to download that information to do analysis on their end needs the study_id prepended.

**Comment by antgonza** [comment]
Agree and have a checkbox to deactivate it.

**Comment by adswafford** [comment]
Yes, agree, we need to be able to roundtrip metadata for edits, so a checkbox option to exclude the qiitaID prefix and the qiita_study_id column is crucial!

**Comment by adswafford** [comment]
I think this issue hasn't come up in a long while and no help traffic about it, so closing.
