### ISSUE TITLE
Ability to change email address

### ISSUE THREAD

**Issue by squirrelo** [qiita-spots/qiita#1506]
We currently use the email address as a primary key for a lot of user-specific things, but this locks a user to the singe email address they used when signing up. We need to change this to a unique identifier, so if a user changes institutions or otherwise changes email addresses, they can still use the same account.

**Comment by antgonza** [comment]
Funny enough 5 days ago I close a similar issue: https://github.com/biocore/qiita/issues/905. If the reasons in that thread do not seem compelling to close this, could you comment why? Thanks!

**Comment by josenavas** [comment]
I was searching that issue to point here and I couldn't find it! Thanks @antgonza for finding it.

**Comment by rob-knight** [comment]
The alternative is you need automated way to move all items associated with
address x to new address y. Can you do this?

Motivation: my qiita acct is linked to my Colorado address which will go
bye-bye soon.

On Oct 15, 2015, at 3:01 PM, Jose Navas <notifications@github.com> wrote:

I was searching that issue to point here and I couldn't find it! Thanks
@antgonza <https://github.com/antgonza> for finding it.

—
Reply to this email directly or view it on GitHub
<https://github.com/biocore/qiita/issues/1506#issuecomment-148535351>.

**Comment by ackermag** [comment]
From an e-mail to Rob:
"I don’t believe there is verification of the email address (a user enters to sign on) - it is just a sign on name.  So (users) will have access to all their studies if they remember to use their original sign-on.  There should be a way to change your sign-on and retain access to all your studies.  There needs to be a way of retaining the history of changes and alias/es. "
Right now the only way to do this is manually on a per study basis.

**Comment by squirrelo** [comment]
Looking at the database, changing from email-keyed users to id-keyed users is not hard to do. Updating the objects to follow that model will take more time though, but is again pretty parallel-izable and not that hard.

**Comment by antgonza** [comment]
decided on 11/01/17: id-keyed users is the future!

**Comment by antgonza** [comment]
This is for sure not an easy fix. Gonna move to March but I think April will make more sense.

Some things to consider and to discuss as a group:
- Which tables we need to change. Looking at [the current version in master of the database](http://htmlpreview.github.io/?https://github.com/biocore/qiita/blob/master/qiita_db/support_files/qiita-db.html), we would need to fix: qiita_user, message_user, study_users, study, analysis, processing_job_workflow, study_tags, processing_job, analysis_users
- Identify the files we need to change to use the new key vs. the email
- Should we still instantiate the User object via the email or use the id. I think email.

**Comment by charles-cowart** [comment]
Migrating comments from #2770:

When a Qiita user changes institutions, their email address will, at some point, stop being a valid email address to notify them of failed jobs, changes to the system, etc.

However, a user's email address also acts as their internal unique id in Qiita, and there is currently no path for the user to change their own email address. Flagging for group input regarding policy, technical solutions.

The standard practice would be to have users have a unique internal numeric id, and map it to an email string that could change without disrupting anything. That seems like a larger effort than what Antonio is proposing, however.

It seems like as long as the user can change their own email address, and we can make that change internally while the user is still logged in, then that would be sufficient.

**Comment by antgonza** [comment]
This is already possible [via CLI](https://github.com/qiita-spots/qiita/blob/master/qiita_db/user.py#L793). Closing.
