### ISSUE TITLE
Describe artifact types in target gene type plugins

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qiita#1701]
See here: https://github.com/biocore/qiita/pull/1697/files/419cd21bcbfd33293a000994454913a43661b0eb#r56911214

**Comment by adswafford** [comment]
@josenavas can you describe more so we can sort out and prioritize this appropriately?

**Comment by antgonza** [comment]
This is pretty old - not sure why we haven't close. Basically, the point was that the plugins were part of _main_ qiita (vs. being in their own repo) and we needed to make sure to "source" the description of the data types in the _documentation_  --- IMOO superseded by current repo split and extra documentation already in place.
