### ISSUE TITLE
Add number of lines to summaries that head can be obtained

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qiita#1900]
Proposed by @antgonza some time ago and forgot to add an issue.

My only concern here is how long will it take to go over the file to count the number of lines. @antgonza Do you think that we should worry about that?

**Comment by adswafford** [comment]
@josenavas  , can you clarify what is meant here?

**Comment by antgonza** [comment]
The idea is to add the number of lines (a proxy for number of sequences) in the summary for sequencing files. This has came up a few times when the upload or the scp dies unexpectedly and the files are corrupted/incomplete.

**Comment by antgonza** [comment]
Should have said, that I haven't see this in a while ...

**Comment by adswafford** [comment]
Unless we have a good way of using this information on the fly or before submitting to a job where the corrupted files will cause problems, then this seems like a lower priority for now.

**Comment by antgonza** [comment]
This information will be useful but agree not high priority ...

**Comment by antgonza** [comment]
This is related to https://github.com/qiita-spots/qtp-sequencing/issues/36 and should be addressed in the plugin; moving there.
