### ISSUE TITLE
Use local authentication system for login

### ISSUE THREAD

**Issue by mdehollander** [qiita-spots/qiita#2020]
I see that Qiita manages its own users. Would it be possible to fit it into an existing ldap or active directory system?
I looked how the Galaxy project is doing this. They first used nginx or apache to get a authenticated username [1], but now they moved to using the python-ldap (https://www.python-ldap.org/) library to authenticate users [2,3]. 
I am not familiar with the qiita codebase, but would it be possible to have also ldap authentication besides the currently used oauth method [4]? Or is there another way to have a user authenticate with already elsewhere registered credentials?

[1] https://wiki.galaxyproject.org/Admin/Config/ApacheExternalUserAuth
[2] https://wiki.galaxyproject.org/Admin/Config/ExternalUserAuth
[3] https://github.com/galaxyproject/galaxy/blob/master/lib/galaxy/auth/providers/ldap_ad.py
[4] https://github.com/biocore/qiita/blob/master/qiita_db/handlers/oauth2.py

**Comment by josenavas** [comment]
hi @mdehollander !

Currently Qiita doesn't support a local authentication system for login. Although it may be possible to add this functionality, some thinking is required to make sure that all cases are covered, and some functionality need to be deactivated if configured that way (i.e. reset passwords, etc).

The [actual login](https://github.com/biocore/qiita/blob/master/qiita_db/user.py#L111) of the user doesn't use oauth2. I don't think we can have both authentication systems side by side, but rather having one or the other.

In any case, I don't foresee this happening before the end of the year. If you're interested on contributing to the project and speed up the implementation of this functionality, we can provide some direction on the relevant code.

Thanks!

**Comment by mdehollander** [comment]
Thanks for the information. I won't be able to contribute before the end of the year either, but its good to know the current status. I will look more into the general system first and if we are going to use it with more users I am willing to help out where I can to get this supported.

**Comment by josenavas** [comment]
Awesome! Thanks @mdehollander

**Comment by colinbrislawn** [comment]
+1 for reusing logins!

**Comment by antgonza** [comment]
With the perspective that only time can give you, I don't think we would add this functionality to main Qiita (UCSD deployment); however, if there is interest in adding this functionality please open a PR. 

Now, another option is to do this via [Globus Auth authentication](https://github.com/qiita-spots/qiita/pull/2939); the only issue with this approach is that it is tricky to share the current authentication and Globus in the same system + there isn't a handbook of how to "easily" transition users and/or deal with users that doesn't have Globus credentials. 

Anyway, closing.
