### ISSUE TITLE
Send a message to the user when his jobs are done

### ISSUE THREAD

**Issue by josenavas** [qiita-spots/qiita#2054]
By default using the internal message system, but allow the user to configure if they want to receive an email.

It was brought up during the Workshop that it will be useful to avoid "polling" the system.

**Comment by antgonza** [comment]
I guess the set up should be for all jobs and not per-job (at creation), right? Also, should this be an option for all users and we should always have on but can be edited on the "edit user info" page?

**Comment by josenavas** [comment]
You mean in a per-workflow basis? No, the idea was per job. And the idea is to use the internal messaging system, but the user can choose to receive emails rather than use the internal messaging system.

**Comment by antgonza** [comment]
Nop. I was thinking that the user will select if they want to receive an email during job creation. Basically that the option is per workflow vs. a general user setting.

**Comment by antgonza** [comment]
@adswafford , @josenavas, what do you guys think?

**Comment by josenavas** [comment]
Not sure, we can discuss on the call today - I would prefer a general user setting.

**Comment by antgonza** [comment]
After discussing we decided that emails will be per workflow (when you hit "Run") and have the option to notify: owner and shared-with. The email is gonna be sent at error of full workflow end.

**Comment by antgonza** [comment]
This issue should be fixed at the same time than: https://github.com/biocore/qiita/issues/2208

**Comment by antgonza** [comment]
This has been addressed and now users can opt in to get messages every time there is a job status change. The option is in the user profile.
