### ISSUE TITLE
add ebi submission plots to the stats page

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qiita#2081]
Something like this:
![screen shot 2017-02-15 at 10 21 31 am](https://cloud.githubusercontent.com/assets/2014559/22986387/9114ee18-f368-11e6-9642-165094338091.png)

**Comment by ackermag** [comment]
Refers to samples submitted?

**Comment by antgonza** [comment]
yup, basically add the example plots to the nightly updates.

**Comment by antgonza** [comment]
In the past, I used to use this kind of plots for my presentations to show the amount of data in Qiita; however, I no longer do this and I use the stats summary:
<img width="594" alt="Screen Shot 2021-05-12 at 12 25 35 PM" src="https://user-images.githubusercontent.com/2014559/118025665-5536a480-b31d-11eb-9277-f5c248353e4b.png">
and the usage plot:
<img width="1461" alt="Screen Shot 2021-05-12 at 12 27 30 PM" src="https://user-images.githubusercontent.com/2014559/118025810-7ac3ae00-b31d-11eb-962c-f656fea5266e.png">

Thus, closing.
