### ISSUE TITLE
Download Drops

### ISSUE THREAD

**Issue by nearinj** [qiita-spots/qiita#3002]
Hello Qiita devs,

I have been trying to download the BIOM and mapping files for the qiita study 10172, however, everytime my download gets to 37% (8.66Gb) the connection to the server is closed.  I have tried on multiple different internet connections and continue to have the same issue.

`index.html?data=biom&study_id  37%[================>                              ]   8.66G  --.-KB/s    in 10m 13s

2020-05-19 17:33:32 (14.5 MB/s) - Connection closed at byte 9302100798. Retrying.`

**Comment by antgonza** [comment]
In the past we have seen a similar issue when the computer goes to sleep; have you tried: https://qiita.ucsd.edu/static/doc/html/faq.html#how-to-solve-download-or-unzip-errors ?

BTW these might also be helpful:
- https://qiita.ucsd.edu/static/doc/html/downloading.html.
- https://qiita.ucsd.edu/static/doc/html/faq.html#do-you-have-specific-qiita-questions

**Comment by nearinj** [comment]
I tried all of those options and tested on both a windows pc, and two different PCs running ubuntu 16.04 and have run into the same issue. The file always stops downloading at that byte... I was able to download another study after a few attempts although I also ran into the connection dropping twice before successfully downloading the files.

**Comment by antgonza** [comment]
Interesting, which command exactly are you using?

**Comment by nearinj** [comment]
On the two different servers: 

I have used:

`wget 'https://qiita.ucsd.edu/public_download/?data=biom&study_id=10423'`

**Comment by antgonza** [comment]
Just a quick note, we are still investigating. It's something specific about one artifact - if you go to https://qiita.ucsd.edu/public/?study_id=10172, you can download all the artifacts except `46193`.

cc: @jdereus

**Comment by nearinj** [comment]
Awesome thanks for the update and the support. I'll go ahead and use that link for the time being.

**Comment by wxgao33** [comment]
Hello, I have been downloading the Biom and mapping files of study 13767 and encountered the same problem. It always fails at 76%. Is there any solutions to this? Thank you!

**Comment by antgonza** [comment]
@wxgao33 Can you share the command you are using?

**Comment by wxgao33** [comment]
wget "https://qiita.ucsd.edu/public_download/?data=biom&study_id=13767" 
I have tried multiple times and it always fails at 76%(363Gb).

**Comment by antgonza** [comment]
@wxgao33, thank you for the command, we are investigating.

**Comment by antgonza** [comment]
A user contacted us via qiita.help letting us know that this was still happening. Then we realized that there was a new mod_zip so we updated both nginx and mod_zip and the user's problems were resolved. Additionally, I just tested the 2 reports here and things seem to also have solved; see notes below. 

Anyway, closing for now. If you encounter this error please open another issue or contact qiita.help.

```
$ wget 'https://qiita.ucsd.edu/public_download/?data=biom&study_id=10172' -O 10172.zip
--2024-01-26 11:57:52--  https://qiita.ucsd.edu/public_download/?data=biom&study_id=10172
Resolving qiita.ucsd.edu (qiita.ucsd.edu)... 10.210.38.19
Connecting to qiita.ucsd.edu (qiita.ucsd.edu)|10.210.38.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 30194647583 (28G) [application/zip]
Saving to: ‘10172.zip’

100%[======================================================================================================================================================================================>] 30,194,647,583 99.7MB/s   in 6m 24s 

2024-01-26 12:04:57 (75.0 MB/s) - ‘10172.zip’ saved [30194647583/30194647583]

$ wget 'https://qiita.ucsd.edu/public_download/?data=biom&study_id=13767' -O 13767.zip
--2024-01-26 12:05:09--  https://qiita.ucsd.edu/public_download/?data=biom&study_id=13767
Resolving qiita.ucsd.edu (qiita.ucsd.edu)... 10.210.38.19
Connecting to qiita.ucsd.edu (qiita.ucsd.edu)|10.210.38.19|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 271825987329 (253G) [application/zip]
Saving to: ‘13767.zip’

100%[=====================================================================================================================================================================================>] 271,825,987,329 79.6MB/s   in 41m 37s

2024-01-26 12:48:39 (104 MB/s) - ‘13767.zip’ saved [271825987329/271825987329]
```
