### ISSUE TITLE
(Meta)analysis mapping file download

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3068]
Hi Qiita team,
it would be handy to download a merged mapping (=sample metadata and/or prep data) file for an analysis like https://qiita.ucsd.edu/analysis/description/33661/. I figure this is what should happen when pressing on "Mapping file"
![image](https://user-images.githubusercontent.com/11960616/106109656-1142d980-614a-11eb-95cb-f416df416fce.png)
However, it looks like the link is either broken or an empty document is generated.

**Comment by antgonza** [comment]
Thank you for reporting. It's one of those easy to fix, annoying bugs; basically not owners can see public analysis but can't download the mapping file; sorry for the inconvenience. We'll fix for the next deployment. 

In the mean time, I have added your gmail to the study and you should be able to download the files.
