### ISSUE TITLE
Processing recommendation links are broken

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3090]
Linked here https://qiita.ucsd.edu/workflows/ 
e.g. https://qiita-rc.ucsd.edu/static/doc/html/processingdata/processing-recommendations.html#metatranscriptome-processing 
I figure the `-rc` is the problem.

**Comment by antgonza** [comment]
Thank you for catching this. 

The nice thing is that this is in the DB and can be changed quickly. Closing as it should be fixed now.
