### ISSUE TITLE
Label WoL/Rep200 Woltka artifacts with prefix or suffix to indicate the database used

### ISSUE THREAD

**Issue by adswafford** [qiita-spots/qiita#3102]
Can we automatically append or prepend 'WoL' or 'rep200' to the artifacts produced from Woltka so that it's clear which db was used? I find myself having to frequently relabel them to try to keep track.

**Comment by antgonza** [comment]
This is actually controlled by the DB via the `naming_order` method in the `Command` object. However, it only allows to take the full parameter, in this case: `'Database': '/opt/genome/qiita_dbs/qp-woltka/wol/WoLr1'`, which IMOO is too much not necessary text.

A kind of hack but possible solution would be to always split and get the last value, if there is a / in the name (AKA file path); thoughts?

**Comment by adswafford** [comment]
That seems reasonable to me to just take the file stem at the end.
