### ISSUE TITLE
Add a "Searching..." bar or text when search is ongoing

### ISSUE THREAD

**Issue by mestaki** [qiita-spots/qiita#3119]
Reproduce the issue:
From the main "View Studies" page, search for a term like "Paulus". It takes about ~7-10 seconds for the page to start showing the results, during which time no indication is made that search is ongoing. This leads to user thinking the search has returned 0 results and they move on to the next search item before the previous search is complete. I suspect this issue will become exaggerated as more data is added and searches take longer.

Propose behavior:
1. Show a "Loading" bar or text when a search is still ongoing, or 
2. Add a "Search" button beside the search field that users click that goes dim when a search is ongoing.

**Comment by mestaki** [comment]
Hey @antgonza,
Awesome this is perfect! Glad it wasn't too much of a hassle to change :)

**Comment by antgonza** [comment]
Thank you for your feedback and review - this will be deployed during this cycle (in a few weeks).
