### ISSUE TITLE
showstopper "trimming" step?

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3125]
when manually composing the workflow, I can add the `split_library_step`, chose parameters and add this step. When I try to do the same for the `trimming` step, no parameter to chose from show up and I cannot continue to compose the workflow :-/

I tried with Chrome and Firefox.

![image](https://user-images.githubusercontent.com/11960616/125620781-b53bc3d3-194a-40ee-8c7b-8df37e0a8939.png)

**Comment by antgonza** [comment]
Thank you for reporting. We also noticed this. The current "solution" is to run that job and then add your other steps, once that one is finished AKA one at the time. Sorry for the inconvenience. We are working on a patch to be deployed soon.

**Comment by antgonza** [comment]
BTW, great issue name! 😃

**Comment by antgonza** [comment]
@sjanssen2, we did a quick deployment over the weekend where we solved this issue. Again, thank you for reporting and let us know if you find anything else.
