### ISSUE TITLE
no "Add New Preparation" button

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3126]
after uploading sample and prep files, I used the sample file to add "Sample Information". Qiita successfully processed the new data, issued a no "env_package" warning in yellow but displayed the new data. Next, I wanted to create a new preparation, however, the according button was not present in the left menu. Only listing all studies and clicking on the right one, updated the menu properly.
That might be confusing for novel users, which cannot anticipate that this button is missing.

**Comment by antgonza** [comment]
Agreed! This is annoying and should be covered when https://github.com/qiita-spots/qiita/issues/2604 is addressed; closing this one and leaving that one open as it has more information. Thank you for your report.
