### ISSUE TITLE
Adonis misleading documentation

### ISSUE THREAD

**Issue by crusher083** [qiita-spots/qiita#3127]
![image](https://user-images.githubusercontent.com/61702053/125636169-00188451-ae28-4d51-b2ed-1ee5ec71b30a.png)

On the contrary to the instruction, no quotation needed during formula encoding. Adding quotation results in error.

**Comment by antgonza** [comment]
Thank you @crusher083; this is an interesting one. Basically, that help comes from the Q2 command, which is trying to guide users in the CLI; however, this is not necessary for GUI as everything is already escaped. 

Out of curiosity, @thermokarst, how do you deal with this scenario in the Q2 GUI.

**Comment by thermokarst** [comment]
> Out of curiosity, @thermokarst, how do you deal with this scenario in the Q2 GUI.

You just don't wrap the param in quotes, like @crusher083 said. The text there doesn't say that quotes are required, just that if there are issues you can wrap in quotes (although I'm sure the text could be altered to be more clear).

**Comment by antgonza** [comment]
Thank you, @thermokarst

**Comment by antgonza** [comment]
@crusher083, I'm going to close this issue but please feel free to follow up in the [Q2 forum](https://forum.qiime2.org/) or opening a PR [here](https://github.com/qiime2/q2-diversity/) to improve the documentation. BTW these are the lines you are [looking for](https://github.com/qiime2/q2-diversity/blob/master/q2_diversity/plugin_setup.py#L775).
