### ISSUE TITLE
Feature request: Renaming nodes on the graph of analysis

### ISSUE THREAD

**Issue by crusher083** [qiita-spots/qiita#3129]
I am currently running an analysis in Qiita. Due to its exploratory nature, it has a lot of steps and the graph becomes hard to manage. 
It would be nice to have the ability to rename nodes to give them some unique description, making it easier to follow. 
![image](https://user-images.githubusercontent.com/61702053/127787437-26d71f3b-9b31-432c-8f7d-da295c2fcdcd.png)

**Comment by mestaki** [comment]
Hi @crusher083 ,

The output nodes' (in white) names can already be edited by clicking the "Edit Name" button.
![image](https://user-images.githubusercontent.com/17439092/127790430-0012f28e-9d5d-49b6-ab16-30fbca5002a6.png)

Does this get you what you need?

**Comment by crusher083** [comment]
@mestaki Thanks for the answer! Wasn't aware of it. Yes, it is what I was searching for. :)
