### ISSUE TITLE
reverse table order

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3133]
currently, entries in Qiita tables are listed according to their "ID" in ascending order, like here:
![image](https://user-images.githubusercontent.com/11960616/129851027-13181a14-191a-41a1-baa0-9c51fed37da6.png)

However, I much more oft need to access the latest entries than older e.g. studies which have already been published. Therefore, it would be handy if either the user could change via personal settings or you might even discuss to change this globally.

**Comment by antgonza** [comment]
Thank you for the feedback. Note that you can click on the headers to re-sort the table; however, I think is worth reconsidering a new sorting, for example: newest study id, then smallest number of artifacts? 

What do you think?

**Comment by sjanssen2** [comment]
@manual re-sorting: exactly, and I am too lazy to hit this arrow all the time :-)
@order: sounds great. If the data are available, one might want to sort by last modification data, but since this is not displayed it might as well confuse the user
