### ISSUE TITLE
Download link description

### ISSUE THREAD

**Issue by haiminen** [qiita-spots/qiita#3134]
When using the "Generate download link" to download several files from a study, the resulting file has a random name and no extension, when fetching it on command line with `wget  https://qiita.ucsd.edu/private_download/dwqa1R...hA==` for example. 
On the other hand in Windows the file seems to get a sensible name `artifact_NNN_NNN-NNN.zip`. 

The downloading instructions ( https://qiita.ucsd.edu/static/doc/html/downloading.html ) did not mention anything related to the archive type or unpacking.
After renaming the downloaded file `dwqa1R...hA==` to `artifact.zip` I was able to unzip it to reveal the study files inside the archive.
Adding documentation on this either next to the download link and/or to the downloading  instructions would be helpful, thank you!

**Comment by antgonza** [comment]
@haiminen, thank you for using Qiita and your suggestion.

What about adding a section here: https://qiita.ucsd.edu/static/doc/html/downloading.html with this:

> Note that all Qiita downloads are zip files but the name of the file will change based on the tool you use to download them. For example if you are using wget, we recommend adding the URL in quotes and using the -O flag to save the file with a correct name; like this: wget "your-qiita-URL" -O your_filename.zip

**Comment by haiminen** [comment]
That looks good to me, thanks!
