### ISSUE TITLE
Fix Trim documentation: it should be keep vs. remove. 

### ISSUE THREAD

**Issue by clairexu010** [qiita-spots/qiita#3142]
Dear developers,

Previously I worked with QIIME1/2 and DADA2 for 16S data processing. Now I'm testing the CMIWorkshop 16S data (demo dataset) on qiita. 

Here I come across 3 questions regarding the data processing on qiita. 

1. How does qiita handle paired-end reads produced with the EMP protocol? Can it join PE reads? If it does, at which step does the joining happen?

- In QIIME, we join PE reads first, then perform the demultiplexing. However, in qiita, the workflow enters the split_libray directly.  

2. The threshold for the trimming of reads during split_libary is not changeable and the default setting is 3. Is there any particular reason that you set it to 3 for all the analysis and do you think the reads will be qualified enough for analysis?

- We usually trim off the bases with Phred quality score<20, which allows for 1% chance of error. 

3. Qiita trims the reads after demultiplexing to a certain length. Based on the documentation from qiita (screenshot below), if I set the parameter to 100, it removes the first 100 base pairs. Is it true? Why remove the first 100 bases rather than the 100 bases at the right end? For Illumina sequencing, usually the quality for the right end is not that good. 

<img width="443" alt="trim" src="https://user-images.githubusercontent.com/72391137/132474951-addf21dd-836d-4c4e-8ea7-1a574b84eaff.png">

Your comments and feedbacks will be highly appreciated. 

Best regards,
Claire

**Comment by antgonza** [comment]
Hi Claire, 

Thank you for your detailed question and thank you for sending this question to our recommended support method: email qiita.help@gmail.com. Anyway, replying here simply for completeness; then I will link this response to your other question via email. 

1. Qiita does _not_  join pair reads; however, we might in the future, [here the open issue for this feature request](https://github.com/qiita-spots/qiita/issues/1118) - also check the links in point 2 as they might help understand more the implications of joining reads for meta-analysis.
2. That's correct, users can _not_ change processing parameters as they matter a lot for the generated feature tables; in other words, using different processing parameters might prevent doing meta-analyses; for more information I would suggest:
   a.  Checking [these reads about](https://qiita.ucsd.edu/static/doc/html/faq.html#do-you-have-meta-analysis-questions        ) meta-analyses
   b. Reading about [the reasoning](https://qiita.ucsd.edu/static/doc/html/processingdata/deblur_quality.html) behind those split libraries parameters selections
   c. Other meta-analysis discussions in the QIIME 2 forum, note that you need to be registered to access them: [thread 1](https://forum.qiime2.org/t/re-combining-data-from-different-sequencing-centers-and-primers/20648/), [thread 2](https://forum.qiime2.org/t/a-question-about-meta-analysis-using-qiime2-dada2-or-qiime1-closed-otu/17587/), [thread 3](https://forum.qiime2.org/t/deblur-vs-dada2-questions/2093/), and [thread 4](https://forum.qiime2.org/t/combining-datasets-with-2-sets-of-primers/3073)
3. Good catch! That's a mistake, it actually **keeps** the 100 first base pairs. I'm going to change the title of this issue to highlight that change. 

Hope this helps.
