### ISSUE TITLE
suggestions for help documentation

### ISSUE THREAD

**Issue by maque4004** [qiita-spots/qiita#3160]
Dear Qiita Team,

Thank you for developing such a great platform!

I met some troubles during my first trial to make data public in Qiita, which was solved with the kindly help of your wonderful team.
Combining my experience, I would like to make the following suggestions.
1. Specify how to contact the Qiime administrator to change the study status in the help documentation.
2. make it clear that the data should comply with the checklist as long as the user want to make the data public.  The current documentation will make the user think that if he/she doesn’t want to submit the data to EBI-ENA, any format is acceptable.
3.  add "physical_specimen_location" and "collection_timestamp" to the sample information file checklist.
4.  add valid options for each columns if possible. For example, "Illumina" is not a valid value for "instrument_model " column in prep info file, the user have to make it more accurate, like "Illumina HiSeq 1000".

Best,
Yichen

**Comment by antgonza** [comment]
Thank you for your suggestions!

**Comment by antgonza** [comment]
I'm currently working on this and I'm not sure where (2) is - where is it confusing? For example, the documentation is:
![Screen Shot 2021-11-19 at 11 59 51 AM](https://user-images.githubusercontent.com/2014559/142676967-8f8859b1-ebd4-4f7c-b125-e1f5abb91ef4.png)

**Comment by maque4004** [comment]
> Qiita allows users to deposit their study, sample, experiment and sequence data to the European Nucleotide Archive (ENA), which is the permanent data repository of the European Bioinformatics Institute (EBI). 

> For each preparation that needs to be uploaded to EBI-ENA we will check:


As a new user, when I read sentences above, I would think that if I only want to make data public in Qiita, the sample information and preparation files may not have to follow the checklist in the documentation.The checklist seems to be only related to EBI-ENA. So I would suggest to make it clear that if the user wants to make data public, he/she should prepare the sample information and preparation file complying with the checklist always.
If only me had this confusion, it may be my problem. Hope it can help.

**Comment by antgonza** [comment]
Thank you for the quick feedback and makes sense. 

Well change:
```
For each preparation that needs to be uploaded to EBI-ENA we will check:
```
to
```
For each preparation that needs to be uploaded to EBI-ENA or become public we will check:
```

Please let us know if you have any other suggestions.
