### ISSUE TITLE
Setting tube_id does not seem to work after a prep has been added

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qiita#3185]
The sample information appears to account for blanks, and Qiita will error saying that "tube_id" is not unique; in the example being exampled, study 13309, the sample metadata in fact appear unique for tube_id and instead it seems that Qiita may be examining "tube_id" for blanks that came in from a prep.

**Comment by antgonza** [comment]
This is now deprecated as we removed the tube_id/specimen_id idea from Qiita: https://github.com/qiita-spots/qiita/pull/3191; and we added in the sequencing processing pipeline (the KL internal pipeline).
