### ISSUE TITLE
tube_id should allow for a stripped leading zero

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qiita#3186]
Matrix tubes use "0363147001" which may get stripped by excel. Qiita needs to account for this, and allow testing of mapping of "0363147001" first, and "363147001 as a fallback.

**Comment by antgonza** [comment]
This is now deprecated as we removed the tube_id/specimen_id idea from Qiita: https://github.com/qiita-spots/qiita/pull/3191; and we added in the sequencing processing pipeline (the KL internal pipeline). Note that the new code also strips for leading zeros.
