### ISSUE TITLE
Zip bomb when unzipping metagenomic data from Qiita

### ISSUE THREAD

**Issue by valentynbez** [qiita-spots/qiita#3221]
Downloaded archives with raw or preprocessed metagenomic data are treated as `zip bombs`. Probably avoidable with `sudo`, but makes it impossible to work with on a multi-user scientific clusters.

**Comment by antgonza** [comment]
Do you have an example of the error, warning or what you are getting? I'm not sure what you mean with `zip bombs`.

**Comment by valentynbez** [comment]
Sorry for not being more verbose. 
After downloading a raw data artifact from Qiita using `wget` and trying to unzip it I receive the following error: 
![image](https://user-images.githubusercontent.com/61702053/201882939-ff4e9477-aba0-4191-ad52-c10193698c96.png)

**Comment by antgonza** [comment]
OK, thank you. 

[Reading online](https://unix.stackexchange.com/a/657373 ) it seems that this could be an issue with the unzip version you are using, do you know which one is it? You can check it via: `unzip -h`.

Now, another option is to set an env variable via `export UNZIP_DISABLE_ZIPBOMB_DETECTION=TRUE` and then trying to uncompress; could you also try this?

**Comment by valentynbez** [comment]
Rather looks like an issue on my side. Thank you.
