### ISSUE TITLE
Deleting artifacts should not move logs/summaries to the upload folder

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qiita#3222]
Currently, when you delete a sequence artifact, the code moves the summary file (qtp-sequencing-validate-data.csv) to the upload folder, which then blocks the upload functionality.

**Comment by antgonza** [comment]
Same thing happens with the feature-table.qza files.

**Comment by charles-cowart** [comment]
move everything that is NOT the two groups of items above.

**Comment by antgonza** [comment]
This is still happening, in specific: qtp-sequencing-validate-data.csv

**Comment by antgonza** [comment]
This was solved on https://github.com/qiita-spots/qiita/pull/3298
