### ISSUE TITLE
Link to Qiime broken

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3225]
The Link to Qiimp in https://qiita.ucsd.edu/static/doc/html/gettingstartedguide/index.html#sample-information-file is broken in the paragraph `tab located at the top of the page is a useful tool for creating Qiita and EBI compatible metadata spreadsheets.`
Found by @mbeck123

**Comment by antgonza** [comment]
Confirmed. Note that the correct link should be: https://qiita.ucsd.edu/iframe/?iframe=qiimp and the incorrect one (which is propagated in several places in the documentation) is https://qiita.ucsd.edu/static/doc/html/qiimp.html.

**Comment by antgonza** [comment]
@mbeck123 and @sjanssen2, thank you for the report.

**Comment by antgonza** [comment]
Looking on a local installation I cannot reproduce this issue; however, the broken link exists in the main deployment. At this point, my guess is that the issue are leftover files from old documentation versions so during the next deployment we should clean all older versions of the documentation by `rm -r qiita_pet/support_files/doc/build/ qiita_pet/static/doc/`; which I already added to deployment instructions.

I'll leave this issue open and close after we can tests in the main deployment.

**Comment by antgonza** [comment]
This issue no longer applies after merging: https://github.com/qiita-spots/qiita/pull/3408.
