### ISSUE TITLE
Additional information in job status change Qiita emails

### ISSUE THREAD

**Issue by mmbryant23** [qiita-spots/qiita#3230]
(Not sure if this is the right place for this!)

It would be beneficial to have additional information in "Job Status Change" emails regarding the artifact that is moving through the workflow pipeline (as well as error emails). This could include prep # (& data type) and Qiita IDs affected and can be located before the "New Status" line:
<img width="924" alt="Screen Shot 2023-01-18 at 4 08 41 PM" src="https://user-images.githubusercontent.com/91337806/213295436-3342ab0d-dcc9-4774-be0a-39b0a01160c0.png">

This is helpful when you are getting multiple emails from multiple jobs you are running, or if you are coming back from out of office and need a refresher on what jobs and projects are being referred to.

**Comment by antgonza** [comment]
Thank you for opening @mmbryant23; the issue should be in qiita and I just moved it.

**Comment by antgonza** [comment]
As a reminder, there are 3 types of input artifacts that a job can use:
1. processing (it has a prep id linked): it should display the study id (link), prep ids, data_type and command name
2. analysis (it has an analysis linked): it should display the analysis id (link)  and command name
3. jobs without input artifact (admins jobs): the command name and parameters submitted

**Comment by charles-cowart** [comment]
@antgonza @mmbryant23 Just an FYI, the line 'New status: Error' line is the subject line of the email, so it's not possible to put something above it. We could change the subject line itself to include the info Antonio mentions above, or make it the first line of the body of the email, above "Error:'.
