### ISSUE TITLE
delete prep fails

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3250]
Hi qiita team,
I am trying to delete an "empty" preparation, i.e. one without artifacts:
![image](https://user-images.githubusercontent.com/11960616/219661039-df9d9562-62c9-4687-b9fd-472e5a082e81.png)

I then get the following error message:
![image](https://user-images.githubusercontent.com/11960616/219661111-5062399c-241e-4e43-bd6b-c97f415aaaf0.png)

This was originally detected by @Timo1B

**Comment by antgonza** [comment]
Thank you for the report. This is caused when the user clicks multiple times in the artifact linkage button or it has multiple windows open and the user starts the linkage in one page and then does the same in another page, and the system (for other reasons) is slow at that time. Note that we have code to block the button and don't allow this to happen but once in a while this could happen. 

Anyway, I reviewed all Qiita to look for this side-effect, leaving the search code here for reference:
```python
from qiita_db.study import Study

for study in Study.iter():
    artifacts = set([a for a in study.artifacts()]) ^ set(
        [a for pt in study.prep_templates() if pt.artifact is not None 
         for a in pt.artifact.descendants.nodes])
    if artifacts:
        print (study.id, [(a.id, a.prep_templates[0].id) for a in artifacts])
```
and found that this has happened 4 times in the last few years. Fixed them all, including deleting your preparation.

Anyway, closing for now but we'll keep an eye open.
