### ISSUE TITLE
Automated signature creation by QIITA on bugsigdb.org

### ISSUE THREAD

**Issue by lwaldron** [qiita-spots/qiita#3251]
https://bugsigdb.org is a Semantic MediaWiki of published microbial signatures from differential abundance studies of host-associated microorganisms. It records various study and experimental details using a controlled vocabulary, including the UBERON anatomy ontology, Experimental Factor Ontology, and NCBI taxonomy. Its contents can be searched on the website by taxon, condition, host species, country, and body site, and downloaded in bulk from the website or through the bugsigdbr Bioconductor package. Authors posting a study on BugSigDB will be able to compare their differential abundance results to all other signatures in BugSigDB, and see annotations of the taxa they find for whether they are typical of certain body sites, common contaminants, or not host-associated.  See [About BugSigDB](https://bugsigdb.org/Project:About) for more information.

BugSigDB has an API (documented [here](https://bugsigdb.org/Help:Editing_using_the_API), on issue tracker [here](https://github.com/waldronlab/BugSigDB/issues/134)). Could QIITA support automatic publishing of differential abundance results on BugSigDB for studies that provide sufficient, controlled metadata?

**Comment by antgonza** [comment]
Hi @lwaldron; good to hear back from you and keep this idea rolling! 

Anyway, I think publishing the results in Qiita would be duplication of data/effort. However, displaying the Qiita study id in [BugSigDB](https://bugsigdb.org/Project:About) would be a good start (this will allow you to make sure that the given study actually exists in Qiita), once you have linked your pages/results to Qiita we could reciprocate. What do you think? Happy to discuss via email, if you prefer.

Best,

**Comment by antgonza** [comment]
Just for the record: @lwaldron, continued the conversation via email.

**Comment by antgonza** [comment]
@lwaldron, thank you for opening this issue and the email discussion.

As a summary: After some discussion via email, we realized that the best way forward is for bugsigdb.org to add to their reports if a study exists in Qiita or not. This decision was made based on the current goals/results-reports of the two systems, as Qiita is mainly focus on the analysis and reporting, as accurately as possible, all the methodological steps.

As a reminder, you can search for public studies using https://github.com/biocore/redbiom or the website directly. Additionally, you can download data from Qiita using these instructions: https://qiita.ucsd.edu/static/doc/html/downloading.html. 

Please reopen, if the bugsigdb.org goals change to fully incorporate other results (like beta/alpha) or have fully detailed analytical steps.
