### ISSUE TITLE
Sample_Validation?

### ISSUE THREAD

**Issue by DrCletusSpucklerMD** [qiita-spots/qiita#3275]
Developers!

Can we expand the 'Sample Validation' functionality to work on 'tube_id' as well as 'sample_name'? Since the wet lab scans in matrix tubes using 'tube_id,' that is a more useful identifier than 'sample_name.'

Currently, when I try and use 'tube_id' as an identifier it gets grouped into 'Extra':
<img width="1792" alt="Screen Shot 2023-03-27 at 6 43 16 PM" src="https://user-images.githubusercontent.com/22571541/228105315-7b81593b-c7ad-42c3-9887-8262d5571d69.png">

**Comment by mmbryant23** [comment]
In addition to the request above, it would be very beneficial if there was a "Duplicate" column that showed if you had any duplicate samples in your list.
This way the wetlab can catch duplicate samples at the plating step, name/format them accordingly, and communicate this information asap to ensure that no delays occur.

Thanks!!
