### ISSUE TITLE
Sequence processing resource requirements are very large for amplicon

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qiita#3280]
It was observed that the resource requests for the processing pipeline, with an amplicon sequencing run, are very large. The amount of resources used is small compared to the request. What I suspect is going on is the same set of resource requirements are used for amplicon as well as shotgun data.

**Comment by antgonza** [comment]
This was solved via the [mg-scripts configuration file](https://github.com/biocore/mg-scripts/blob/master/sequence_processing_pipeline/configuration.json#L8-L24) as we currently process amplicon with bcl2fastq and other with bcl-convert.
