### ISSUE TITLE
High priority job submissions

### ISSUE THREAD

**Issue by wasade** [qiita-spots/qiita#3281]
Work through the processing pipeline is high priority, and should always be treated as time sensitive. If necessary, these jobs should preempt other work on the compute cluster. In discussion, it came up that this is feasible with the establishment of a high priority partition. Processing jobs should submit to that partition once defined. Given that this is a different partition than what other Qiita work submits to, it would be valuable to ensure job monitoring is unaffected.

**Comment by antgonza** [comment]
After review and internal discussion we assigned new/better resource allocation to the pipelines and we are keeping an eye open in case this issue happens again (which hasn't since the modifications); thus, closing for now.
