### ISSUE TITLE
allow per user_level and per_user slurm submission flags

### ISSUE THREAD

**Issue by antgonza** [qiita-spots/qiita#3322]
It would be ideal if we could allow extra or replace flags for slurm job submissions based on the:
- user_level: if the job belongs to group X add/update certain flags or change queue 
- per_user: if the job belongs to user Y add/update certain flags or change queue 

One of the values we would like to use is:
All_other_users. --nice[=+10000]
Admin_users --nice[=+5000]
Wetlab_users --nice[=0]

**Comment by jdereus** [comment]
My concern with the proposed, is that the wetlab_users should likely trump all others.  It has been repeatedly argued that their jobs need to go first.  So if an admin user is running a bunch of jobs, (for what reason?), they will continue to block.

Thanks,
Jeff D

From: Antonio Gonzalez ***@***.***>
Reply-To: qiita-spots/qiita ***@***.***>
Date: Monday, October 16, 2023 at 1:45 PM
To: qiita-spots/qiita ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [qiita-spots/qiita] allow per user_level and per_user slurm submission flags (Issue #3322)


It would be ideal if we could allow extra or replace flags for slurm job submissions based on the:

  *   user_level: if the job belongs to group X add/update certain flags or change queue
  *   per_user: if the job belongs to user Y add/update certain flags or change queue

One of the values we would like to use is:
All_other_users. --nice[=+10000]
Admin_users --nice[=+5000]
Wetlab_users --nice[=0]

**Comment by jdereus** [comment]
I don’t know at this time.  Just providing my thoughts on it.  I would prefer to not see a solution that still locks jobs out after all the work being put in.

Thanks,
Jeff D

From: Antonio Gonzalez ***@***.***>
Reply-To: qiita-spots/qiita ***@***.***>
Date: Monday, October 16, 2023 at 1:52 PM
To: qiita-spots/qiita ***@***.***>
Cc: jdereus ***@***.***>, Comment ***@***.***>
Subject: Re: [qiita-spots/qiita] allow per user_level and per_user slurm submission flags (Issue #3322)


Got it; what would be the proposed solution for that scenario?
