### ISSUE TITLE
Upload to ENA-EBI queries?

### ISSUE THREAD

**Issue by marwa38** [qiita-spots/qiita#3335]
Hi team 

1- I am aiming to do a comparative analyses for my datasets using [MGnify ](https://www.ebi.ac.uk/metagenomics/)which is considered an option avaiable on ENA for the uploaded data. Using qitta will still allow me to have access to ENA before the data being public? (asking as I will adjust a late release date while doing some analyses using their [MGnify](https://www.ebi.ac.uk/metagenomics/).

2- Could you please do a video on how to use qiita to upload our datasets to ENA? I believe this will ease the process for us and spread to others how can't do the upload onto ENA using their way. 

3- some datasets that will be uploaded to ENA would be available for meta-analyses? if they are recently uploaded but not released yet to be public? knowing that they are all mine. 

4- other datasets that are already public on SRA could be imported and be used on qiita or request that to have them on qiita?

5- if I uploaded to ENA without using qiita and the data are not yet public, could I use them for meta-analyses in qiita?

Thanks for letting me know
Marwa

**Comment by marwa38** [comment]
Thanks so much for the answers. 
Regarding MGnify, I forwarded an email from ENA; maybe that clarifies it more (my email:m.tawfik.19@abdn.ac.uk). They do comparative analyses on MGnify, which would be nice to try. MGnify basically does some analyses when you request it (attached screenshot). 
MGnify doesn't need the data to be public; just uploaded on ENA. 
Do you think we could now use MGnify after uploading via Qiita?
![image](https://github.com/qiita-spots/qiita/assets/68851733/938ea98b-ecd9-4593-8060-baaa6dc9f9b9)
What about the release date control, can I do that from your side (using Qiita)?

**Comment by marwa38** [comment]
Hi @antgonza 

Here is my metadata example (.zip) I attached with queries, hope you could help with that as I need to submit the today (hopefully). I am not sure when I am supposed to expect that I got my project id that I will add into the manuscript? 

[qiita metadata_ENA-EBI.zip](https://github.com/qiita-spots/qiita/files/13684162/qiita.metadata_ENA-EBI.zip)

1- Regarding your [processing recommendations](https://qiita.ucsd.edu/static/doc/html/processingdata/processing-recommendations.html) I used for 'Target gene barcoded sequencing' is dada2 (recommendations are deblur or clustering), does that sound ok?

2- what is the difference?? between those under b. and c.:

Under b.	Minimal information:

- `host_subject_id`: Atlantic salmon 
- `taxon_id` : 8030
- `scientific_name`: Salmo salar 

Under c.	Extra minimal information for host associated studies:
- `host_scientific_name`: Salmo salar
- `host_common_name`: Atlantic salmon
- `host_taxid`: 8030

3- where should I add info about 16S rRNA data? e.g.,
`host_taxid`: bacteria and archae
![image](https://github.com/qiita-spots/qiita/assets/68851733/c98a50ce-ffb5-4cf9-bab4-339414b099f2)
below screenshot from website you shared `full list`: 
![image](https://github.com/qiita-spots/qiita/assets/68851733/b7bd8111-cb7e-4bad-af97-7f67beb92728)

4- Does `sample_name` considered part of the metadata table I want to attach under b.	Minimal information:

- `sample_name`: e.g., 3_1_4_P for pyloric-MMV-T1-Rep4 (as sample.ID)
or should it be general thing like Gut? but how then it differs from `env_material`: Gut
Or it is better to add metadata table as empo1, empo2, etc? e.g.,
![image](https://github.com/qiita-spots/qiita/assets/68851733/4ead7f74-5d2d-48b5-9252-fc8d61f546c1)
should I change the column titles in this case to be empo_1, etc 

5- I have gut samples but also water and feed samples
so what to do regarding `env_biome`: Freshwater biome? since the fish was in freshwater and the water collected is also freshwater, what do you think?

6- what is required here `elevation, latitude, longitude`? you mean of the country?

7- leaving `sex` as null value is ok? 

8- I think it is ok to leave this as 'host-associated' rather than 'water' although both samples were included?
![image](https://github.com/qiita-spots/qiita/assets/68851733/66b8f14c-69d2-421e-8603-802d3d2bfee2)

9- any definitions for these terms? 
![image](https://github.com/qiita-spots/qiita/assets/68851733/705d37aa-da5a-4356-bfb9-7ce9985901dd)
my design is feeding different diets (marine[M] and vegetable[V]) at different time points and sampling at those time points. I think `multiple interventions, real` works for me? quick fig for my desgin
![image](https://github.com/qiita-spots/qiita/assets/68851733/21d57eef-32ea-445b-93b9-1e5fedd647ac)

10- it is mandatory to add the abstract while the manuscript haven't been published yet?

11- the project is collaborative between two universities and we have PI and CO-PI and this work was done in the CO-PI lab. So I think it is better to add the CO-PI name? I can't find how I can add more than one. In the ENA-EBI, I can see that I can add more than one person including the first author (me), any advice?
![image](https://github.com/qiita-spots/qiita/assets/68851733/f0cdd88d-6858-4754-83eb-c32a9cb78e4d)

12- for the `library_construction_protocol`: library preparation kit used is Nextera XT, is that how it is supposed to be answered?

I read all instructions and happy if you have advice to focus into if I am missing something.

**Comment by antgonza** [comment]
Hi @marwa38, 

In case you missed it from [the documentation](https://qiita.ucsd.edu/static/doc/html/checklist-for-ebi-ena-submission.html):
![Screen Shot 2023-12-15 at 5 30 20 AM](https://github.com/qiita-spots/qiita/assets/2014559/b1f7d06f-f076-45f7-b277-91c9d60fd92f).

Thus, please send an email to the qiita help account.

Additionally, note ENA sent an announcement yesterday:
![Screen Shot 2023-12-15 at 5 35 50 AM](https://github.com/qiita-spots/qiita/assets/2014559/0f2f0974-357d-438e-922a-18f1cd7c7c69)

**Comment by antgonza** [comment]
I'm going to close this thread as now is a submission request that should be handled via email.

**Comment by marwa38** [comment]
I sent you my queries via email already.
It is not a last-minute submission! As I have been preparing for this for long time, aif you can help, that is great, if you can't that is fine. Anyway my queries are mainly regarding qiita documentation that is unclear to me. 
Do think that we need to contact ENA-EBI regarding the submission, I think it is automated.
