### ISSUE TITLE
how to activate private plugins?

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3367]
If I get it right from the source code, there are some actions that are implemented as a "private" plugin, e.g. https://github.com/qiita-spots/qiita/blob/57d1b146729223da9daa286a1cc75db6f2923746/qiita_ware/private_plugin.py#L139C5-L139C20

After setting up an new instance in non-test mode, a software "Qiita" with version "alpha" is listed for admin users with software and commands flagged as inactive. I wonder how I best activate these commands? I could not find the plugin typical start and configure scripts like e.g. https://github.com/qiita-spots/qp-deblur/tree/master/scripts

However, when starting qiita, first all plugins get deactivated and then those which have a config file get activated:
https://github.com/qiita-spots/qiita/blob/57d1b146729223da9daa286a1cc75db6f2923746/scripts/qiita#L374-L375

**Comment by antgonza** [comment]
Private plugins are meant to be internal Qiita commands. In other words, there should provide direct "commands" or other non internal functionality. So, they can't be activated or deactivated and just live in the database. 

Anyway, as they are internal they are simply populated to the database, see patch `58.py` and these lines:
```
    parameters = {'artifact': ['integer', None]}
    create_command(qiita_plugin, "delete_artifact",
                   "Delete an artifact", parameters)
```

**Comment by antgonza** [comment]
@sjanssen2, did my previous reply answer your question?

**Comment by sjanssen2** [comment]
yes it did. Thank you @antgonza
