### ISSUE TITLE
add settings table to DB schema

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3368]
The Qiita DB Schema file qiita_db/support_files/qiita-db.html is extremely helpful to understand the design of the database. I just found that there are additional tables (outside the qiita.* schema) that are also used by qiita, e.g. `settings` https://github.com/qiita-spots/qiita/blob/57d1b146729223da9daa286a1cc75db6f2923746/qiita_db/environment_manager.py#L351
Could you add these tables to the HTML overview?

**Comment by antgonza** [comment]
Yes, I'm not actually sure why is not there; my only guess is that it only shows the qiita.* tables ... anyway, I think is fine to add.
