### ISSUE TITLE
hard coded emails should be part of the configuration

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3375]
https://github.com/qiita-spots/qiita/blob/57d1b146729223da9daa286a1cc75db6f2923746/qiita_db/processing_job.py#L902-L906

**Comment by antgonza** [comment]
There at least a couple of scenarios where we send emails to alert people (based on previous discussions and request) but I agree that they might be better in a configuration file. I'll change the title of this issue.

**Comment by antgonza** [comment]
Fixed here: https://github.com/qiita-spots/qiita/pull/3384
