### ISSUE TITLE
Store social IDs for user

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3404]
In our today's consortium meeting, the question was raised if a user can store social IDs for their qiita profile, e.g. ORCID. If I look at the DB structure, qiita can't at the moment. Have you any plans / opinions on doing so or would you welcome code contributions towards this end?

**Comment by antgonza** [comment]
Any extra user information that can be public will be good to add. Contribution will be great!

**Comment by sjanssen2** [comment]
I am thinking of ORCID, google scholar and researchgate. Do you want to add further services?
Regarding the DB architecture, I see two ways:
1. simply extend the qiita.qiita_user table by additional columns. Pro: simple, con: too many changes as services might fluctuate relatively often
2. create a new table to collect these infos. Pro: many to many relation possible (although one user should have only once accession), no changes in qiita.qiita_user table necessary. Con: more complicated SQL queries.

Any preference or maybe even suggestion of a third strategy?

**Comment by antgonza** [comment]
I think those to start with sound good. What about adding a single jsonb column (maybe "socials"?) to the qiita.qiita_user table with those keys and empty values as default? That should allow us to modify as we need.

**Comment by sjanssen2** [comment]
closing as #3412 was merged
