### ISSUE TITLE
private_download returns filepath list instead of file content

### ISSUE THREAD

**Issue by sjanssen2** [qiita-spots/qiita#3407]
Hi @antgonza,
when I generate a public link of an artifact in my Qiita instance:
![image](https://github.com/qiita-spots/qiita/assets/11960616/d61acd8b-16bd-4592-b4fa-f0baeddc2289)
I do get a link, but using this link does not return a zip archive with the files as content, but is a plain textfile that lists the filepaths from the filesystem, like:

```
- 346916 /protected/Demultiplexed/41/seqs.fastq.gz Demultiplexed/41/seqs.fastq.gz
- 69187 /protected/Demultiplexed/41/seqs.fasta.gz Demultiplexed/41/seqs.fasta.gz
- 425721 /protected/Demultiplexed/41/seqs.demux Demultiplexed/41/seqs.demux
- 22029 /protected/Demultiplexed/41/index.html Demultiplexed/41/index.html
- 6247 /protected/templates/6_prep_9_20240507-134645.txt mapping_files/41_mapping_file.txt
```
Since I read function names like `_write_nginx_file_list` in https://github.com/qiita-spots/qiita/blob/13eafdf1a2eb0c8b5d4019ad294b7490cd396139/qiita_pet/handlers/download.py#L137 I figure this is probably due to a misconfiguration of my NGINX. Could you provide an example nginx config section?
Many thanks!

**Comment by sjanssen2** [comment]
Or is it a nginx module that is missing? If so, which one do you use?

**Comment by antgonza** [comment]
Yup, nginx: https://github.com/evanmiller/mod_zip. Note that the library is not perfect and could be improved, suggest checking these:
- https://qiita.ucsd.edu/static/doc/html/faq.html#how-to-solve-download-or-unzip-errors
- https://github.com/qiita-spots/qiita/issues/3002
- https://github.com/qiita-spots/qiita/issues/2920

**Comment by sjanssen2** [comment]
wasn't easy to compile / install a modified nginx version, therefore I left some notes to the INSTALL.md file in #3409 It works now on our instance :-)
